<a href="https://colab.research.google.com/github/herotam77/PortfolioProjects/blob/main/2_Copy_of_Toyota_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"ToyotaCorolla.csv", encoding = 'latin-1')

In [ ]:
df.drop("Id", axis=1, inplace=True)

In [ ]:
df.head()

,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Color,...,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar
0,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,Blue,...,1,1,1,0,0,0,1,0,0,0
1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,Silver,...,1,0,1,0,0,0,1,0,0,0
2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,Blue,...,0,0,1,0,0,0,1,0,0,0
3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,Black,...,0,0,1,0,0,0,1,0,0,0
4,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,Black,...,1,1,1,0,1,0,1,0,0,0

In [ ]:
df.columns

Index(['Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'cc', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Tow_Bar'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1435 entries, 0 to 1434
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Model             1435 non-null   object
 1   Price             1435 non-null   int64
 2   Age_08_04         1435 non-null   int64
 3   Mfg_Month         1435 non-null   int64
 4   Mfg_Year          1435 non-null   int64
 5   KM                1435 non-null   int64
 6   Fuel_Type         1435 non-null   object
 7   HP                1435 non-null   int64
 8   Met_Color         1435 non-null   int64
 9   Color             1435 non-null   object
 10  Automatic         1435 non-null   int64
 11  cc                1435 non-null   int64
 12  Doors             1435 non-null   int64
 13  Cylinders         1435 non-null   int64
 14  Gears             1435 non-null   int64
 15  Quarterly_Tax     1435 non-null   int64
 16  Weight            1435 non-null   int64
 17  Mfr_Guarantee     1435 non-null   int64
 18  BOVAG_Guarantee   1435 non-null   int64
 19  Guarantee_Period  1435 non-null   int64
 20  ABS               1435 non-null   int64
 21  Airbag_1          1435 non-null   int64
 22  Airbag_2          1435 non-null   int64
 23  Airco             1435 non-null   int64
 24  Automatic_airco   1435 non-null   int64
 25  Boardcomputer     1435 non-null   int64
 26  CD_Player         1435 non-null   int64
 27  Central_Lock      1435 non-null   int64
 28  Powered_Windows   1435 non-null   int64
 29  Power_Steering    1435 non-null   int64
 30  Radio             1435 non-null   int64
 31  Mistlamps         1435 non-null   int64
 32  Sport_Model       1435 non-null   int64
 33  Backseat_Divider  1435 non-null   int64
 34  Metallic_Rim      1435 non-null   int64
 35  Radio_cassette    1435 non-null   int64
 36  Tow_Bar           1435 non-null   int64
dtypes: int64(34), object(3)
memory usage: 414.9+ KB

In [ ]:
df.isnull().sum()

Model               0
Price               0
Age_08_04           0
Mfg_Month           0
Mfg_Year            0
KM                  0
Fuel_Type           0
HP                  0
Met_Color           0
Color               0
Automatic           0
cc                  0
Doors               0
Cylinders           0
Gears               0
Quarterly_Tax       0
Weight              0
Mfr_Guarantee       0
BOVAG_Guarantee     0
Guarantee_Period    0
ABS                 0
Airbag_1            0
Airbag_2            0
Airco               0
Automatic_airco     0
Boardcomputer       0
CD_Player           0
Central_Lock        0
Powered_Windows     0
Power_Steering      0
Radio               0
Mistlamps           0
Sport_Model         0
Backseat_Divider    0
Metallic_Rim        0
Radio_cassette      0
Tow_Bar             0
dtype: int64

In [ ]:
df['Model'].value_counts()

TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-Doors         107
TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-Doors          83
TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors            79
TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA 4/5-Doors           70
TOYOTA Corolla 1.6 16V SEDAN LINEA TERRA 4/5-Doors           43
                                                           ...
TOYOTA Corolla 2.0 D4D 90 5DR TERRA 4/5-Doors                 1
Â TOYOTA Corolla 1.6 16V VVT I SEDAN TERRA AUT4 4/5-Doors      1
Â TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors                1
TOYOTA Corolla 1.9 D Linea Terra 2/3-Doors                    1
TOYOTA Corolla 1.3 Linea Terra 4/5-Doors                      1
Name: Model, Length: 371, dtype: int64

In [ ]:
import re
text ="TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-Doors"
int(re.findall(r'[0-9]',text)[0])

1

In [ ]:
def extractengine(text):
  digits = re.findall(r'[0-9]',text)
  if len(digits) == 0:
    return 0
  if type(digits) == list:
    return int(digits[0])
  else:
    return int(digits)

In [ ]:
import re
def  extract_engine(text):
    digits =re.findall(r'[0-9]',text)
    if len(digits)==0:
      return 0
    if type(digits)==list:
      return  int(digits[0])
    else:
      return int(digits)

In [ ]:
df['Model'] =df['Model'].map(extract_engine)
df.head()

,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Color,...,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar
0,2,13500,23,10,2002,46986,Diesel,90,1,Blue,...,1,1,1,0,0,0,1,0,0,0
1,2,13750,23,10,2002,72937,Diesel,90,1,Silver,...,1,0,1,0,0,0,1,0,0,0
2,2,13950,24,9,2002,41711,Diesel,90,1,Blue,...,0,0,1,0,0,0,1,0,0,0
3,2,14950,26,7,2002,48000,Diesel,90,0,Black,...,0,0,1,0,0,0,1,0,0,0
4,2,13750,30,3,2002,38500,Diesel,90,0,Black,...,1,1,1,0,1,0,1,0,0,0

In [ ]:
import re

def extractengine(text):
    if not isinstance(text, str):
        return 0

    digits = re.findall(r'[0-9]', text)
    if len(digits) == 0:
        return 0
    return int(digits[0])

df['Model'] = df['Model'].map(extractengine)

print(df.head())

   Model  Price  Age_08_04  Mfg_Month  Mfg_Year     KM Fuel_Type  HP  \
0      0  13500         23         10      2002  46986    Diesel  90
1      0  13750         23         10      2002  72937    Diesel  90
2      0  13950         24          9      2002  41711    Diesel  90
3      0  14950         26          7      2002  48000    Diesel  90
4      0  13750         30          3      2002  38500    Diesel  90

   Met_Color   Color  ...  Central_Lock  Powered_Windows  Power_Steering  \
0          1    Blue  ...             1                1               1
1          1  Silver  ...             1                0               1
2          1    Blue  ...             0                0               1
3          0   Black  ...             0                0               1
4          0   Black  ...             1                1               1

   Radio  Mistlamps  Sport_Model  Backseat_Divider  Metallic_Rim  \
0      0          0            0                 1             0
1      0          0            0                 1             0
2      0          0            0                 1             0
3      0          0            0                 1             0
4      0          1            0                 1             0

   Radio_cassette  Tow_Bar
0               0        0
1               0        0
2               0        0
3               0        0
4               0        0

[5 rows x 37 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
mylabel =LabelEncoder()
car['Fuel_Type'] =mylabel.fit_transform(car['Fuel_Type'])
car['Color'] =mylabel.fit_transform(car['Color'])
car.head()

NameError: name 'car' is not defined

In [ ]:
y =car['Price'].values
X =car.drop('Price',axis=1).values

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.linear_model import LinearRegression
model =LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

In [ ]:
from sklearn.decomposition import PCA
mypca =PCA(n_components=19)
X_train =mypca.fit_transform(X_train)
X_test =mypca.transform(X_test)
X_train.shape

In [ ]:
from sklearn.preprocessing import MinMaxScaler
myscaler =MinMaxScaler()
X_train =myscaler.fit_transform(X_train)
X_test =myscaler.transform(X_test)

In [ ]:
import numpy as np
np.sum(mypca.explained_variance_ratio_)

AttributeError: 'PCA' object has no attribute 'explained_variance_ratio_'

0.94 ááá©ááááááááá áááá¡á á áá